######################################################################
# Automatically generated by qmake (2.01a) Tue Jun 18 02:38:08 2013
######################################################################

TEMPLATE = app
TARGET = kubach
DEPENDPATH += .
INCLUDEPATH += .

QMAKE_CXXFLAGS += -std=c++0x
QT += core gui opengl
LIBS += -lGLU

# Input
HEADERS += cube.h main_window.h player.h
SOURCES += cube.cpp main.cpp main_window.cpp player.cpp
